### ISSUE TITLE
How to start transformationActivity without previous Activity or Fragment has TrasformationLayout

### ISSUE THREAD

**Issue by Woochang4862** [skydoves/TransformationLayout#48]
I want to start TransformationActivity(in my project, DetailActivity about movie) through Notification's pending intent. 
So do I, this exception occurs 

Caused by: java.lang.IllegalArgumentException: TransformationLayout.Params must not be a null. check your intent key value is correct.
                                                                                                    	at com.skydoves.transformationlayout.TransitionExtensionKt.onTransformationEndContainer(TransitionExtension.kt:38)
                                                                                                    	at com.skydoves.transformationlayout.TransformationAppCompatActivity.onCreate(TransformationAppCompatActivity.kt:27)

Do you have any solution, if you have please let me know. Thank you!

**Comment by skydoves** [comment]
There's no way to achieve this for now since a View should provide meaningful information to the target Activity/Fragment. I will let you know once I find any solutions for tihs.
